"""improve rate limit policy and rules

Revision ID: 27aa67adc81d
Revises: 869c7c4f5605
Create Date: 2026-08-29 18:45:16.477574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27aa67adc81d'
down_revision: Union[str, Sequence[str], None] = '869c7c4f5605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rate_limit_policies_is_active'), 'rate_limit_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_rate_limit_rules_is_active'), 'rate_limit_rules', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_rules_is_active'), table_name='rate_limit_rules')
    op.drop_index(op.f('ix_rate_limit_policies_is_active'), table_name='rate_limit_policies')
    # ### end Alembic commands ###
